# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('region', models.CharField(blank=True, choices=[('NE US', 'NE US'), ('SE US', 'SE US'), ('NW US', 'NW US'), ('SW US', 'SW US')], max_length=255, null=True, verbose_name='Region of Farm')),
            ],
        ),
    ]
